version: "3.0"

services:
  postgres:
    image: sruthicps/postgres:shorturl
    restart: "always"
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
